In [70]:
import pandas as pd

In [71]:
df=pd.DataFrame({"land":[1,3,5,30,60],"Price":[1,3,7,35,70]})
df

land  Price
0     1      1
1     3      3
2     5      7
3    30     35
4    60     70

In [72]:
sum_x=df["land"].sum()
sum_x

99

In [73]:
sum_x**2

9801

In [74]:
sum_y=df["Price"].sum()
sum_y

116

In [75]:
a=df["land"]**2
a

0       1
1       9
2      25
3     900
4    3600
Name: land, dtype: int64

In [76]:
b=a.sum()
b

4535

In [77]:
product=df['land']*df['Price']
p=product.sum()
p

5295

In [78]:
m=(5*p-(sum_x*sum_y))/(5*b-sum_x**2)                          # m =  N Σ(xy) − Σx Σy / N Σ(x2) − (Σx)2
m

1.1644399565014758

In [79]:
b=(sum_y-(m*sum_x))/5
b                                                            #   b =  Σy − m Σx / N

0.1440888612707795

In [80]:
#x=df["land"].values.reshape(-1,1)
#x

In [81]:
x=df[["land"]]
x

land
0     1
1     3
2     5
3    30
4    60

In [82]:
y=df[['Price']]
y

Price
0      1
1      3
2      7
3     35
4     70

In [83]:
from sklearn.linear_model import LinearRegression 

In [84]:
linmodel=LinearRegression()
linmodel.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [85]:
linmodel.score(x,y)*100

99.95487510257458

In [86]:
linmodel.predict([[60]])

array([[70.01048625]])

In [87]:
linmodel.intercept_

array([0.14408886])

In [88]:
linmodel.coef_

array([[1.16443996]])

# Another Example

In [50]:
d=pd.DataFrame({"person":[1,3,5,7,9],"age":[21,22,23,24,20],"height":[154,157,167,178,148],"weight":[40,45,68,65,42]})
d

person  age  height  weight
0       1   21     154      40
1       3   22     157      45
2       5   23     167      68
3       7   24     178      65
4       9   20     148      42

In [57]:
x1=d[["height",'weight']]
x1

height  weight
0     154      40
1     157      45
2     167      68
3     178      65
4     148      42

In [58]:
y1=d[['age']]
y1

age
0   21
1   22
2   23
3   24
4   20

In [59]:
from sklearn.linear_model import LinearRegression 


In [60]:
linmodel1=LinearRegression()
linmodel1.fit(x1,y1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [64]:
linmodel1.predict([[154,40]])

array([[21.07979274]])

In [65]:
linmodel1.score(x1,y1)*100

95.42479270296404

In [66]:
linmodel.intercept_

array([0.2])

In [67]:
linmodel.coef_

array([[7.3]])

In [68]:
from sklearn.metrics import r2_score

 ## r2score (y_actual,y_predict) ==== syntax

In [89]:
y

Price
0      1
1      3
2      7
3     35
4     70

In [90]:
y_predict=linmodel.predict(x)
y_predict

array([[ 1.30852882],
       [ 3.63740873],
       [ 5.96628864],
       [35.07728756],
       [70.01048625]])

In [91]:
r2_score(y,y_predict)

0.9995487510257458

In [92]:
from sklearn.metrics import mean_squared_error

In [93]:
mean_squared_error(y,y_predict)

0.3152244834550258

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [105]:
x_train.shape

(3, 1)

In [106]:
from sklearn.linear_model import LinearRegression 

In [107]:
linmodel=LinearRegression()

In [108]:
linmodel.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [109]:
linmodel.score(x_train,y_train)*100

99.85207100591718

In [110]:
from sklearn.metrics import r2_score

In [111]:
y_predict=linmodel.predict(x_test)
y_predict

array([[ 3.94871795],
       [69.71794872]])

In [112]:
r2_score(y_test,y_predict)

0.9995635470385714

In [113]:
from sklearn.metrics import mean_squared_error

In [114]:
mean_squared_error(y_test,y_predict)

0.48980933596318427